Repository SiEPIC/openEBL-2025-02, pull requests merged in 2025-02, with the labels that each got.

#161 This is version 1 of my design
  submissions/EBeam_rafael_pangilinan.gds
Labels: greeted

#160 Add files via upload
  submissions/EBeam_hugh1337.gds
Labels: greeted

#163 Revert "First Draft"
  ELEC413_PaigeHall.gds
Labels: greeted

#170 This is my layout.
  submissions/EBeam_FangjiaZhu.gds
Labels: greeted

#178 Layout for fabrication
  submissions/EBeam_MChetanSR.gds
Labels: greeted

#176 Add files via upload
  submissions/EBeam_snewman_CDCs_G_v02.gds
Labels: greeted

#171 Initial design
  submissions/EBeam_smargala.gds
Labels: greeted

#183 tadessem_Ver_1
  submissions/EBeam_tadessem_v_1.gds
Labels: greeted

#27 Add Project Draft (Lucas Henderson)
  submissions/ELEC413_LucasHenderson5212.oas
Labels: greeted

#9 Final Chip 1 Layout
  submissions/ELEC413_BriannaGopaul.gds
Labels: greeted

#196 somids pull request
  submissions/EBeam_somids.gds
Labels: greeted

#119 Chip 1 layout
  submissions/ELEC413_HaomingGao.gds
Labels: greeted

#219 first_file_upload
  submissions/OpenEBL_FelixGabrielAlbertMessmer.gds
Labels: greeted

#216 This is my first design to submit.
  submissions/EBeam_takeshikamijo.gds
Labels: greeted

#76 My design
  submissions/EBeam_Guanlin_Z.gds
Labels: greeted

#233 Request to merge
  submissions/Ebeam_Kexin_99.gds
Labels: greeted

#229 Add files via upload
  submissions/EBeam_sastreit.gds
Labels: greeted

#228 Design project 1
  submissions/EBeam_bmorga7.gds
Labels: greeted

#227 Layout submission for Ian Scogin
  submissions/EBeam_iscogin.gds
Labels: greeted

#240 My design
  submissions/EBeam_y00yang.gds
Labels: greeted

#231 updated file 120225
  submissions/EBeam_kielyo.gds
Labels: greeted

#238 wcai05submission
  submissions/openEBL_wcai05_Williamy2n10.oas
Labels: greeted

#264 Add files via upload
  submissions/EBeam_zackeriahchristie.gds
Labels: greeted

#262 Photonics Project
  submissions/EBeam_cjdavis493.gds
Labels: greeted

#257 d_bristow36 layout submission
  submissions/EBeam_d_bristow36.oas
Labels: greeted

#258 c
  submissions/Ebeam_SJOHN27.gds
Labels: greeted

#254 edX Final Layout Submission - khughe4
  submissions/EBeam_khughe4.gds
Labels: greeted

#248 Final Layout For Fabrication
  submissions/EBeam_cjlong22.gds
Labels: greeted

#271 draft design
  submissions/EBeam_adinathguduru.gds
Labels: greeted

#277 Add files via upload - waive verification
  submissions/EBeam_JudsonRS.GDS
  submissions/EBeam_JudsonRT.GDS
  submissions/EBeam_JudsonRU.GDS
  submissions/EBeam_JudsonRV.gds
Labels: greeted

#275 Add wgloss DOEs
  submissions/UBC_static.oas
Labels: greeted

#297 Submission Julian Garcia Fernandez
  submissions/EBeam_jgfernandez.gds
Labels: greeted

#296 This is my layout submission.
  submissions/EBeam_tareid_03.gds
Labels: greeted

#326 Add files via upload
  submissions/EBeam_serdarogut.gds
Labels: greeted

#314 Add files via upload
  submissions/EBeam_jonkere_RndPfNanobeams.oas
  submissions/EBeam_jonkere_RndReNanobeams.oas
  submissions/EBeam_jonkere_SqPfNanobeams.oas
  submissions/EBeam_jonkere_SqReNanobeams.oas
Labels: greeted

#324 This is my final layout design v2
  submissions/EBeam_xusouto_v1.oas
Labels: greeted

#346 My design final version
  submissions/EBeam_zxhstar.gds
Labels: greeted

#236 Clayhold Design
  submissions/EBeam_jclayhold.gds
Labels: bug, greeted

#363 Pull Request for : Design of Gayathri Vinod, username - gayathry__v
  submissions/EBeam_gayathry__v.gds
Labels: greeted

#372 MasihB MR MZI
  submissions/masihb_crow1_mzi_v1.gds
  submissions/masihb_crow1_v1.gds
  submissions/masihb_crow2_mzi_v1.gds
  submissions/masihb_crow2_mzi_v2.gds
  submissions/masihb_crow2_mzi_v3.gds
  submissions/masihb_crow2_v1.gds
  submissions/masihb_crow2_v2.gds
  submissions/masihb_crow2_v3.gds
Labels: greeted

#342 Semifinal review (just four hours remaining)...
  submissions/EBeam_Mackattackx.gds
Labels: greeted

#307 different configurations of the circuit
  submissions/OpenEBL_FelixGabrielAlbertMessmer.gds
  submissions/OpenEBL_FelixGabrielAlbertMessmerB.gds
  submissions/OpenEBL_FelixGabrielAlbertMessmerC.gds
  submissions/OpenEBL_FelixGabrielAlbertMessmerD.gds
  submissions/OpenEBL_FelixGabrielAlbertMessmerE.gds
Labels: review required

#130 Uploaded layout files
  submissions/EBeam_ELEC413_SHERWINTIU.gds
  submissions/EBeam_ELEC413_SherwinTiu.gds
  submissions/EBeam_ELEC413_Sherwin_Tiu_v2.gds
  submissions/ELEC413_SherwinTiu.pdf
Labels: bug
